spring.application.name=whereuat-backend
server.port=8080
spring.data.mongodb.uri=mongodb+srv://vnsshashwat:9iQPrdcNVXgCFGw4@whereuat.kc0ycnc.mongodb.net/?retryWrites=true&w=majority&appName=whereuat
spring.data.mongodb.database=whereuat